name: Build and Release Go Binary

on:
  release:
    types:
      - created
permissions:
  contents: write
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, windows]
        go_version: [1.21]
        architecture: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the Go binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.architecture }} go build -o netdisco-${{ matrix.os }}-${{ matrix.architecture }} -ldflags="-w -s" cli/main.go

      - name: Upload Go binary as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: netdisco-${{ matrix.os }}-${{ matrix.architecture }}
          path: netdisco-${{ matrix.os }}-${{ matrix.architecture }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            netdisco-linux-amd64
            netdisco-darwin-amd64
            netdisco-darwin-arm64
            netdisco-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
